### ISSUE TITLE
ALL CAPS mode never returns any words

### ISSUE THREAD

**Issue by weiweihuanghuang** [ninastoessinger/word-o-mat#3]
Isn't it supposed to convert the text to UPPER instead of finding uppercase words?
I fixed it in the Glyphs app version but not familiar with the RF https://github.com/schriftgestalt/word-o-mat/pull/1/commits/24116553b007a900d71896ebae8d90ef5b063e22

**Comment by weiweihuanghuang** [comment]
Wait I just realised I need to enter caps letters, the error didn't come up when I was using GREP mode for somereason

**Comment by ninastoessinger** [comment]
Yeah some have gotten confused about this, not quite sure how to make it clearer. It converts the words to upper but that happens before matching to / checking against whatever you input as required etc, so those need to be in caps too. The idea also being that if you want to test an “a” that’s really not the same as wanting to test an “A”.
